### ISSUE TITLE
More visual notification of PATENTROOT misconfiguration

### ISSUE THREAD

**Issue by gtfierro** [funginstitute/patentprocessor#1]
When testing for the existence of the PATENTROOT environment variable, we use `logging.error` to notify the user of the problem and how it is temporarily fixed for the duration of the unit tests, but this will not become known to the user unless they look at the unit test log. 

If we want to make this more visible, we can replace `logging.error` with a `print` statement, or change the debugging level of the Python logger for the unit tests and use `logging.info` instead. Any suggestions?

https://github.com/funginstitute/patentprocessor/blob/master/test/test_parse_config.py#L31

**Comment by doolin** [comment]
Configure logger to point to stdout.

On Sun, Dec 23, 2012 at 5:17 PM, Gabe Fierro notifications@github.comwrote:

> When testing for the existence of the PATENTROOT environment variable, we
> use logging.error to notify the user of the problem and how it is
> temporarily fixed for the duration of the unit tests, but this will not
> become known to the user unless they look at the unit test log.
> 
> If we want to make this more visible, we can replace logging.error with a
> print statement, or change the debugging level of the Python logger for
> the unit tests and use logging.info instead. Any suggestions?
> 
> https://github.com/funginstitute/patentprocessor/blob/master/test/test_parse_config.py#L31
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/funginstitute/patentprocessor/issues/1.

## 

primus inter parse

**Comment by gtfierro** [comment]
Fixed in https://github.com/funginstitute/patentprocessor/commit/dc0939872033446df477f728c0392e8e87a1e701
