### ISSUE TITLE
Name parsing inconsistencies

### ISSUE THREAD

**Issue by gtfierro** [funginstitute/patentprocessor#11]
From an email from Sampsa:

> So far, I have noticed the following inconsistencies across names:
> 
> 1) Accented letters are either missing (e.g., "Rémy" becomes "R my")
> or replaced by description (e.g. "Rémy" becomes "R acute over e my")
> or replaced by the same letter without accent (e.g., "Rémy" becomes
> "Remy"). All three versions of the name "Rémy" are found in your data.
> 
> 2) Last name prefixes (e.g., "van der", "von", "de") sometimes appear
> at the beginning of the last name, sometimes at the end of the first
> name.
> 
> The 1999 NBER data seems to be consistent in dropping the accents from
> letters and having last name prefixes at the beginning of the last
> name. My colleague here has two commercial patent databases and one of
> them seems to have the accented letters with the accents and the other
> without accents even when the same name is missing the letter or has a
> description instead of the letter in your data (for a very small
> sample of names, so I can't say really how consistent they are).

**Comment by gtfierro** [comment]
Regarding the first part of this issue (the accents in names), it seems that the removal of accented letters is by design, as suggested by the [unittests](https://github.com/funginstitute/patentprocessor/blob/master/test/test_ascit.py) for the `ascit` function called by the clean phase on the parsed data. 

The `ascit` function is only called during the cleaning phase and the first_name, last_name and street fields on the inventor table, and on the assignee field in the assignee table.

**Comment by doolin** [comment]
I'm surprised it's not called on city or country as well.

On Mon, Feb 25, 2013 at 2:54 PM, Gabe Fierro notifications@github.comwrote:

> Regarding the first part of this issue (the accents in names), it seems
> that the removal of accented letters is by design, as suggested by the
> unittestshttps://github.com/funginstitute/patentprocessor/blob/master/test/test_ascit.pyfor the
> ascit function called by the clean phase on the parsed data.
> 
> The ascit function is only called during the cleaning phase and the
> first_name, last_name and street fields on the inventor table, and on the
> assignee field in the assignee table.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/funginstitute/patentprocessor/issues/11#issuecomment-14081514.

## 

primus inter parse

**Comment by gtfierro** [comment]
City and country are cleaned by lib/locFunc.cityctry and lib/locFunc.uniasc, which seem to operate in a similar fashion to ascit, but don't seem to touch accents. I can't find any unittests for those functions either.

**Comment by doolin** [comment]
Yeah, I didn't everything I wanted covered with unit tests. Should be fairly easy to set up though. DRY-ing it all out will be tedious.

**Comment by gtfierro** [comment]
Should be fixed as of merging in the new_parser branch in af0c49e75
