### ISSUE TITLE
patent abstracts not parsing for 2005-2013

### ISSUE THREAD

**Issue by laironald** [funginstitute/patentprocessor#17]
none of the abstract data appears to be parsed. I ran the following query to check

```
select year(date),count(*) from patent where abstract="" group by year(date)
```

this produces the same counts as the query below 

```
select year(date),count(*) from patent group by year(date)
```

I manually checked a few records and this is also confirmed

**Comment by gtfierro** [comment]
This was an issue related to how the parser believed the tags were nested. Should be fixed as of fb8f3ef4
