### ISSUE TITLE
Preferred text encoding for XML parsing

### ISSUE THREAD

**Issue by gtfierro** [funginstitute/patentprocessor#4]
In parsing the XML documents, particularly in when creating the [list of citations](https://github.com/funginstitute/patentprocessor/blob/new_xml_parsing/lib/new_xml_parsing/xml_driver.py#L172), I run into the case where the old parsing code will return something like `URL: &lt;www.early2bed.com&gt;. (3 pages)`, but it seems better to just return the unescaped version, i.e. `URL: <www.early2bed.com>. (3 pages)`. Should I focus on maintaining continuity with the old code, or use the unescaped characters?

**Comment by doolin** [comment]
Use your discretion, document it in the code, leave this ticket open for a
while until we see what transpires.

On Thu, Jan 10, 2013 at 9:48 PM, Gabe Fierro notifications@github.comwrote:

> In parsing the XML documents, particularly in when creating the list of
> citationshttps://github.com/funginstitute/patentprocessor/blob/new_xml_parsing/lib/new_xml_parsing/xml_driver.py#L172,
> I run into the case where the old parsing code will return something like URL:
> &lt;www.early2bed.com&gt;. (3 pages), but it seems better to just return
> the unescaped version, i.e. URL: <www.early2bed.com>. (3 pages). Should I
> focus on maintaining continuity with the old code, or use the unescaped
> characters?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/funginstitute/patentprocessor/issues/4.

## 

primus inter parse

**Comment by gtfierro** [comment]
It doesn't even look like there is a consistent escaping/unescaping for the strings pulled out by the current parser. At the very least, the behavior doesn't seem to be explicitly specified, so the escaped characters in the current parser are either the result of some regex replace gone wrong or are somehow being put through a filter as part of some default behavior of the libraries he is using. In my work with `xml.sax`, I've found that characters are unescaped by default.

Essentially, any attempt to "choose sides" is going to break compatibility.

**Comment by doolin** [comment]
Then we don't escape anything. Keep the chicken  beaks everywhere.

If we find later we need to escape, we'll escape everything.

If it's easier for now to punt on this, punt.

On Fri, Jan 11, 2013 at 11:05 AM, Gabe Fierro notifications@github.comwrote:

> It doesn't even look like there is a consistent escaping/unescaping for
> the strings pulled out by the current parser. At the very least, the
> behavior doesn't seem to be explicitly specified, so the escaped characters
> in the current parser are either the result of some regex replace gone
> wrong or are somehow being put through a filter as part of some default
> behavior of the libraries he is using. In my work with xml.sax, I've
> found that characters are unescaped by default.
> 
> Essentially, any attempt to "choose sides" is going to break compatibility.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/funginstitute/patentprocessor/issues/4#issuecomment-12158634.

## 

primus inter parse

**Comment by gtfierro** [comment]
Okay; I'm now explicitly unescaping all content we parse out of the XML. Since the rewrite is essentially finished, I'll move the relevant bits of the xml parsing rewrite into the master branch's test directory for future integration work, but won't replace the production parser just yet.

**Comment by doolin** [comment]
Please post a note on the disambiguation list - at some point - explaining the issue and decision.

**Comment by gtfierro** [comment]
Will do -- closing the issue for now. We can reopen if this problem comes up again.

**Comment by gtfierro** [comment]
Turns out it's not XML escaping, he's returning HTML escaped characters which is why I didn't recognize it.

**Comment by doolin** [comment]
There may be a good reason for that. If so, let's document it.

On Fri, Jan 11, 2013 at 1:33 PM, Gabe Fierro notifications@github.comwrote:

> Turns out it's not XML escaping, he's returning HTML escaped characters
> which is why I didn't recognize it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/funginstitute/patentprocessor/issues/4#issuecomment-12164577.

## 

primus inter parse

**Comment by gtfierro** [comment]
It's the default behavior for `xml.sax`'s `.toxml()` method, which isn't used everywhere (thus the inconsistent behavior). I'll make sure to HTML escape all content, and then document it in the code and in a post to the group.

**Comment by doolin** [comment]
Add a tracker story for this one as well.
