### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by billyeh** [funginstitute/patentprocessor#60]
## Consolidate.py
- Line 26: loc, NoneType object, has no attribute 'state'

**Comment by gtfierro** [comment]
For the `geolocation_data.sqlite3` problem, try downloading the updated database from [https://s3.amazonaws.com/fungpatdownloads/geolocation_data.7z](https://s3.amazonaws.com/fungpatdownloads/geolocation_data.7z)

**Comment by gtfierro** [comment]
Thanks for the notes on installation issues. I'll try them out on a fresh Ubuntu VM to test them.

**Comment by billyeh** [comment]
Yeah, thanks. The updated location table has the missing column, so that should fix it.

**Comment by gtfierro** [comment]
Any reason why this has been reopened?

**Comment by billyeh** [comment]
Yeah, I got rid of the old stuff, just reopened it for that new error. Sorry, I'm still trying to get familiar with the code base - seems like alchemy can find the database and fields fine, but is it possible that a rawlocation might not have a location foreign key..?

**Comment by gtfierro** [comment]
Can you re-file it under a new issue instead of editing the current one? Also, please note what inputs you're using and what version of the code that produce the error.
