### ISSUE TITLE
Missing locations while running consolidate.py?

### ISSUE THREAD

**Issue by billyeh** [funginstitute/patentprocessor#64]
Steps to reproduce:
- Clone latest patentprocessor master branch
- Install dependencies
- Download and place [location table](https://s3.amazonaws.com/fungpatdownloads/geolocation_data.7z) in patentprocessor/lib/ and place [ipg130101.xml](http://www.google.com/googlebooks/uspto-patents-grants-text.html) in patentprocessor/
-  Run `parse.py`, `clean.py`, and `consolidate.py`

Resulting error:
line 26 of `consolidate.py`: loc, NoneType object, has no attribute 'state'

**Comment by billyeh** [comment]
I'm not sure if this is a very high priority issue - seems like some rawlocation has quite a few null foreign keys to the location table. There were notices while running clean.py that there were some cities that weren't found in the location table, though, so maybe that was it. Should we have a way to avoid the null error in that case?

**Comment by gtfierro** [comment]
I was talking with @vadskye about this problem, so it's a known issue, but it's nice to have a set input that recreates the issue. I'll adjust the `consolidate.py` code to account for the null location.
