### ISSUE TITLE
Consolidate script looking for gyear that's not passed in by integration tests?

### ISSUE THREAD

**Issue by billyeh** [funginstitute/patentprocessor#71]
The integration test for consolidate.py doesn't work because `consolidate.py` is looking for 

```
gyear = sys.argv[1]
```

which isn't passed in from the bash script, `consolidate_integration.sh`. Am I just missing something here?

Otherwise, I can either add the arguments where consolidate is used, or take it out, since it's just used for filtering.

(The same problem also seems to occur in `start.py` just calling consolidate without passing in the year.)

**Comment by gtfierro** [comment]
This will be fixed in a pull request from my fork

**Comment by gtfierro** [comment]
Fixed as of #72
