### ISSUE TITLE
google stopped updating the patent list

### ISSUE THREAD

**Issue by haohua** [funginstitute/patentprocessor#87]
Hi guys, 

have you noticed that the google link stopped updating the patent file:
https://www.google.com/googlebooks/uspto-patents-applications-text.html
the most recent application file is still on ipa150319.zip 

do you find the same issue, or any reason for so?

thanks
andy

**Comment by gtfierro** [comment]
You're going to want to look at ReedTech http://patents.reedtech.com/pgrbft.php
